# permissions for end users to edit harborclustertraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborclustertrait-editor-role
rules:
- apiGroups:
  - goharbor.io
  resources:
  - harborclustertraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goharbor.io
  resources:
  - harborclustertraits/status
  verbs:
  - get
